export enum FlowState {
  WELCOME = "WELCOME",
  APPLICANT_FORM = "APPLICANT_FORM",
  LINK_CONNECT = "LINK_CONNECT",
  REPORT_PENDING = "REPORT_PENDING",
  REPORT_REFRESH_PENDING = "REPORT_REFRESH_PENDING",
  EMPLOYMENT_REFRESH_PENDING = "EMPLOYMENT_REFRESH_PENDING",
  REPORT_READY = "REPORT_READY",
}
